## Onaje Baxley
## 6/26/18
##
## Following ClusterRole represents a cluster-wide ability to read pods,
## deployments, replicasets, namespaces, services, etc.

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-all
rules:
- apiGroups: ["", "*", "apps", "extensions"]
  resources: [
      "pods",
      "pods/status",
      "pods/log",
      "replicationcontrollers",
      "replicationcontrollers/scale",
      "replicationcontrollers/status",
      "replicationcontrollers.extensions/scale",
      "services",
      "namespaces",
      "namespaces/status",
      "deployments",
      "deployments.apps",
      "deployments.apps/scale",
      "deployments.extensions",
      "deployments.extensions/scale",
      "statefulsets",
      "statefulsets.apps",
      "statefulsets.apps/scale",
      "replicasets",
      "replicasets.apps",
      "replicasets.apps/scale",
      "replicasets.extensions/scale"
  ]
  verbs: ["get", "watch", "list"]
---

## The following resource allows for automatic binding of the "deploy-mgmt"
## default service account (the User under which pods from the "deploy-mgmt"
## namespace assume) with the read-all role defined above.

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployments-reader
subjects:
  - kind: User
    name: system:serviceaccount:deploy-mgmt:default
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: read-all
  apiGroup: rbac.authorization.k8s.io

